# Generated by Django 3.1.1 on 2020-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('CurrencyCode', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Currency Code')),
                ('CurrencyName', models.CharField(max_length=100, verbose_name='Currence Name')),
                ('Currency_Symbol', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Currencies',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=50, verbose_name='Service Name')),
                ('Enabled', models.BooleanField(default=False, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
